version: "3.7"
services:
  app:
    build:
      args:
        user: your_user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: base
    container_name: base-app-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - base

  db:
    image: mysql:8.0.0
    container_name: base-db-mysql
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: base
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: your_user_password
      MYSQL_USER: your_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - base

  nginx:
    image: nginx:alpine
    container_name: base-nginx-server
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - base

networks:
  base:
    driver: bridge
